import type { Metadata } from "next";
import { geistMono, geistSans } from "./fonts/fonts";
import clsx from "clsx";

import "./styles/normalize.css";
import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={clsx(geistSans.variable, geistMono.variable)}>
        {children}
      </body>
    </html>
  );
}
