import type { Metadata } from 'next';
import { geistMono, geistSans } from './fonts/fonts';
import clsx from 'clsx';

import { MobileProvider } from './utils/MobileContext/MobileContext';
import { isMobileServerSide } from './utils/MobileContext/isMobileServerSide';
import { ScrollSmootherInit } from './utils/GSAP/ScrollSmootherInit';

import './styles/normalize.css';
import './styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={clsx(geistSans.variable, geistMono.variable)}>
        <MobileProvider initialIsMobile={isMobileServerSide()}>
          <ScrollSmootherInit>{children}</ScrollSmootherInit>
        </MobileProvider>
      </body>
    </html>
  );
}
